### ISSUE TITLE
Rot13 is crashing

### ISSUE THREAD

**Issue by h2odriving** [takeshixx/deen#22]
the use of rot13 chrash the application, if used for encoding or decoding.

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/deen/widgets/encoder.py", line 306, in <lambda>
    self.encoding_combo.currentIndexChanged.connect(lambda: self.action(self.encoding_combo))
  File "/usr/lib/python3.6/site-packages/deen/widgets/encoder.py", line 494, in action
    self.next.content = encoded
  File "/usr/lib/python3.6/site-packages/deen/widgets/encoder.py", line 86, in content
    assert isinstance(data, (bytearray, bytes))
AssertionError
[1]    8019 abort (core dumped)  deen
```

**Comment by takeshixx** [comment]
Fixed in 93693c7fba539fe36689449d4ad5a9d9ea2dbc64, thanks for reporting.
