### ISSUE TITLE
Dependency dicttoxml is Missing in AUR Package

### ISSUE THREAD

**Issue by SvenTo** [takeshixx/deen#36]
deen (1.7.1.3e6f82f-1) require dicttoxml as dependency. However, the AUR packing is missing this dependency at the moment.

```
% deen
Traceback (most recent call last):
  File "/usr/bin/deen", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'dicttoxml' distribution was not found and is required by deen
```

**Comment by takeshixx** [comment]
The reason why it is not included is that `python-dicttoxml` is only available in AUR. Currently, the PKGBUILD only contains packages in `depends` which are available via pacman. Not sure if depends supports AUR packages?

However, the plan is to abandon the `deen-git` package in favor of a new `deen` package which just installs deen from PyPI. This would make it easier to install deen and all dependencies because the PyPI package installs everything that is installable via pip, and the more complicated dependencies (like keystone and capstone engine) can be installed via PKGBUILD dependencies. But I'm not sure yet if this is the best solution. I'm open for suggestions.

**Comment by SvenTo** [comment]
The common AUR helpers will resolve AUR packages, too. Also, if ``python-dicttoxml`` is installed manually from the PKGBUILD, pacman has no problem with resolving the dependency, too. So this should be no problem. However, you're right that it is not a perfect solution to rely on a third-party AUR package.
