### ISSUE TITLE
deen UI crashing during start in  QtCore.QMetaObject.connectSlotsByName(DeenEncoderWidget)

### ISSUE THREAD

**Issue by SvenTo** [takeshixx/deen#41]
The deen UI is crashing recently on ArchLinux (using the AUR package) during start in  ``QtCore.QMetaObject.connectSlotsByName(DeenEncoderWidget)``:
```
AttributeError: __getattribute__

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 8, in <module>
    sys.exit(main())
  File "/home/sven/git/deen/deen/main.py", line 111, in main
    ex = DeenGui(plugins=pl)
  File "/home/sven/git/deen/deen/gui/core.py", line 30, in __init__
    self.widgets.append(DeenEncoderWidget(self))
  File "/home/sven/git/deen/deen/gui/encoder.py", line 30, in __init__
    self.ui.setupUi(self)
  File "/home/sven/git/deen/deen/gui/widgets/ui_deenencoderwidget.py", line 175, in setupUi
    QtCore.QMetaObject.connectSlotsByName(DeenEncoderWidget)
SystemError: <built-in function connectSlotsByName> returned a result with an error set
```

**Comment by SvenTo** [comment]
Probably related: https://github.com/glue-viz/glue/commit/09e8d2834d4b8fc2fdeeefca6b0acbd50c9c8af4

**Comment by takeshixx** [comment]
Seems like the #42 fixed the error. Thanks for the contribution!
